version: '2'
services:

 web:
    build: ./nodejs
    container_name: mynodejsssl
    volumes:
      - ./myapp:/usr/src/app
      - ./nodejs/certs:/etc/certs
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js,jade server.js'
    ports:
      - "80:8080"
      - "443:8443"
      - "5001:8001"
    environment:
      - SSL_EMAIL="richard.cheso@gmail.com"
      - SSL_DOMAINS="supermegaquest.com"
      - SSL_ENABLED="true"
      - SSL_PROD="false"
       

    